export type Feature = { title: string; body: string };
export type Step = { step: string; title: string; body: string };
export type Faq = { q: string; a: string };
export type Person = { name: string; role: string; body: string; initials: string };

export type SiteCopy = {
  langTag: string;
  localeName: string;
  meta: {
    siteName: string;
    tagline: string;
    homeTitle: string;
    homeDescription: string;
  };
  nav: {
    employers: string;
    nurses: string;
    about: string;
    jobs: string;
    insights: string;
    contact: string;
    cta: string;
    portal: string;
    menu: string;
    close: string;
    langLabel: string;
  };
  common: {
    more: string;
    back: string;
    callUs: string;
    writeUs: string;
    officeHours: string;
    officeHoursValue: string;
    whatsapp: string;
    faqTitle: string;
    skip: string;
  };
  home: {
    eyebrow: string;
    h1: string;
    lead: string;
    ctaPrimary: string;
    ctaSecondary: string;
    trust: string[];
    heroBadges: { value: string; label: string }[];
    statsTitle: string;
    stats: { value: string; label: string }[];
    servicesEyebrow: string;
    servicesTitle: string;
    servicesLead: string;
    services: (Feature & { href: string; linkLabel: string })[];
    processEyebrow: string;
    processTitle: string;
    processLead: string;
    steps: Step[];
    audienceEyebrow: string;
    audienceTitle: string;
    audience: {
      title: string;
      body: string;
      bullets: string[];
      cta: string;
      href: string;
    }[];
    proofEyebrow: string;
    proofTitle: string;
    proofLead: string;
    proof: Feature[];
    missionEyebrow: string;
    missionTitle: string;
    missionBody: string;
    missionQuote: string;
    missionAuthor: string;
    faq: Faq[];
    ctaTitle: string;
    ctaBody: string;
  };
  employers: {
    eyebrow: string;
    h1: string;
    lead: string;
    ctaPrimary: string;
    ctaSecondary: string;
    painEyebrow: string;
    painTitle: string;
    painLead: string;
    pains: Feature[];
    stepsEyebrow: string;
    stepsTitle: string;
    stepsLead: string;
    steps: Step[];
    includedEyebrow: string;
    includedTitle: string;
    included: Feature[];
    recognitionEyebrow: string;
    recognitionTitle: string;
    recognitionBody: string;
    recognitionBullets: string[];
    costTitle: string;
    costBody: string;
    faq: Faq[];
    ctaTitle: string;
    ctaBody: string;
  };
  nurses: {
    eyebrow: string;
    h1: string;
    lead: string;
    ctaPrimary: string;
    ctaSecondary: string;
    promiseEyebrow: string;
    promiseTitle: string;
    promiseLead: string;
    promises: Feature[];
    stepsEyebrow: string;
    stepsTitle: string;
    steps: Step[];
    requirementsTitle: string;
    requirementsLead: string;
    requirements: string[];
    documentsTitle: string;
    documents: string[];
    guaranteeTitle: string;
    guarantees: Feature[];
    faq: Faq[];
    ctaTitle: string;
    ctaBody: string;
  };
  about: {
    eyebrow: string;
    h1: string;
    lead: string;
    storyTitle: string;
    story: string[];
    valuesEyebrow: string;
    valuesTitle: string;
    values: Feature[];
    teamEyebrow: string;
    teamTitle: string;
    teamLead: string;
    team: Person[];
    partnersTitle: string;
    partnersLead: string;
    partners: { name: string; body: string; href: string }[];
    ctaTitle: string;
    ctaBody: string;
  };
  contact: {
    eyebrow: string;
    h1: string;
    lead: string;
    addressTitle: string;
    address: string[];
    directTitle: string;
    formTitle: string;
    formLead: string;
  };
  jobs: {
    eyebrow: string;
    h1: string;
    lead: string;
    filterAll: string;
    filterCategory: string;
    filterRegion: string;
    filterType: string;
    resultsOne: string;
    resultsMany: string;
    empty: string;
    emptyCta: string;
    cardCta: string;
    detailAbout: string;
    detailTasks: string;
    detailProfile: string;
    detailBenefits: string;
    detailApply: string;
    detailApplyLead: string;
    facts: {
      location: string;
      type: string;
      german: string;
      salary: string;
      start: string;
      category: string;
    };
    similar: string;
    noSalary: string;
  };
  insights: {
    eyebrow: string;
    h1: string;
    lead: string;
    readingTime: string;
    empty: string;
    related: string;
    audience: { employer: string; candidate: string; both: string };
  };
  form: {
    name: string;
    email: string;
    phone: string;
    company: string;
    facilityType: string;
    headcount: string;
    timeframe: string;
    message: string;
    messagePlaceholder: string;
    country: string;
    profession: string;
    germanLevel: string;
    experience: string;
    privacy: string;
    privacyLink: string;
    submit: string;
    submitting: string;
    successTitle: string;
    successBody: string;
    error: string;
    required: string;
    optional: string;
    headcountOptions: string[];
    timeframeOptions: string[];
    facilityOptions: string[];
    germanLevelOptions: string[];
    experienceOptions: string[];
  };
  footer: {
    blurb: string;
    pages: string;
    legal: string;
    more: string;
    portal: string;
    social: string;
    rights: string;
    langNote: string;
  };
  legal: {
    impressumTitle: string;
    privacyTitle: string;
    termsTitle: string;
    germanNotice: string;
  };
};
